[general]
cpus = 16
editor = "nvim"
doas = false
language = "en-US"

[aur]
build = "/home/ten/.cache/aura/builds"
cache = "/home/ten/.cache/aura/cache"
clones = "/home/ten/.cache/aura/packages"
hashes = "/home/ten/.cache/aura/hashes"
chroot = []
ignores = []
git = false
hotedit = false
shellcheck = true
diff = true
delmakedeps = true
clean = true
warn_unknowns = true
noconfirm = false
nocheck = false
skipdepcheck = false
reverse = false

[backups]
snapshots = "/home/ten/.cache/aura/snapshots"
automatic = true
